version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - EMAIL=cubb.lama@gmail.com
      - URL=cubbk.cc
      - SUBDOMAINS=www,booky,api.booky
      - VALIDATION=http
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booky
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/data
  server:
    build: ./server
    restart: always
    depends_on:
      - db
    ports:
      - "4001:4001"
    env_file:
      - ./server/.env
  client:
    build: ./client
    restart: always
    depends_on:
      - server
    ports:
      - "3000:3000"
volumes:                         
  db_data:
