version: "3"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: booky
    ports:
      - "3306:3306"
    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/mysql/data
  server:
    build: ./server
    restart: always
    depends_on:
      - db
    ports:
      - "4001:4001"
    env_file:
      - ./server/.env
  client:
    build: ./client
    restart: always
    depends_on:
      - server
    ports:
      - "3000:3000"
volumes:                         
  db_data:
