version: "3"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booky
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/data
  server:
    build: ./server
    depends_on:
      - db
    ports:
      - "4001:4001"
    env_file:
    - server-variables.env
  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "3000:80"
    env_file:
    - client-variables.env
volumes:
  db_data:
